from __future__ import annotations
from datetime import datetime, timezone
from app.clinical.interview import build_follow_up_questions
from app.clinical.missing_information import detect_missing_information
from app.clinical.red_flags import detect_red_flags
from app.clinical.scoring import calculate_risk_score
from app.clinical.uncertainty import calculate_uncertainty
from app.core.metrics import metrics
from app.core.version import EVIDENCE_CORPUS_VERSION, MODEL_NAME, MODEL_VERSION, PROMPT_VERSION
from app.schemas.triage import PatientInput, TriageResponse

def analyze_patient(patient: PatientInput) -> TriageResponse:
    # Canonical Week 6 deterministic entry point. The safety engine is authoritative.
    red_flags = detect_red_flags(patient)
    missing_information = detect_missing_information(patient)
    risk_score = calculate_risk_score(patient, red_flags)
    uncertainty = calculate_uncertainty(missing_information)

    critical_flags = [flag for flag in red_flags if flag.severity == "critical"]

    if critical_flags:
        level = "EMERGENCY"
        confidence = max(0.90, 1.0 - uncertainty)
        recommendations = ["Immediate in-person clinical assessment is warranted."]
        follow_up_questions = []
    else:
        follow_up_questions = build_follow_up_questions(patient)
        if follow_up_questions:
            level = "INSUFFICIENT_INFORMATION"
            confidence = max(0.0, 1.0 - uncertainty)
            recommendations = ["Provide the requested information and then reassess."]
        elif risk_score >= 50:
            level = "URGENT"
            confidence = max(0.0, 1.0 - uncertainty)
            recommendations = ["Prompt clinical assessment is recommended."]
        elif risk_score >= 20:
            level = "SAME_DAY"
            confidence = max(0.0, 1.0 - uncertainty)
            recommendations = ["Clinical assessment should occur the same day."]
        else:
            level = "ROUTINE"
            confidence = max(0.0, 1.0 - uncertainty)
            recommendations = ["Routine clinical follow-up may be appropriate based on the available information."]

    result = TriageResponse(
        created_at=datetime.now(timezone.utc).isoformat(),
        triage_level=level,
        summary="Assessment generated by the ClinicalTriage v2 deterministic safety engine. This is decision support, not a diagnosis.",
        red_flags=red_flags,
        recommendations=recommendations,
        missing_information=missing_information,
        follow_up_questions=follow_up_questions,
        confidence=confidence,
        risk_score=risk_score,
        ai_assisted=False,
        evidence_corpus_version=EVIDENCE_CORPUS_VERSION,
        model_name=MODEL_NAME,
        model_version=MODEL_VERSION,
        prompt_version=PROMPT_VERSION,
    )
    metrics.observe_triage(result.triage_level)
    return result
