from app.schemas.triage import (
    PatientInput,
    TriageResponse )

from app.clinical.red_flags import (
    detect_red_flags )

from app.clinical.missing_information import (
    detect_missing_information )

from app.clinical.scoring import (
    calculate_risk_score )

from app.clinical.uncertainty import (
    calculate_uncertainty )

from app.clinical.questions import (
    generate_follow_up_questions
)

def analyze_patient(
    patient: PatientInput) -> TriageResponse:

    # Step 1: Detect clinical red flags

    red_flags = detect_red_flags(patient)

    # Step 2: Determine missing information

    missing_information = ( detect_missing_information(patient) )

    # Step 3: Calculate internal risk score

    risk_score = calculate_risk_score( patient, red_flags )

    # Step 4: Calculate uncertainty

    uncertainty = calculate_uncertainty(
        missing_information )

    # Step 5: Emergency override
    # Critical red flags always override ordinary
    # missing-information logic.

    critical_flags = [
        flag
        for flag in red_flags
        if flag.severity == "critical"
    ]
    if critical_flags:
        triage_level = "EMERGENCY"
    elif any(
        item.priority == "critical"
        for item in missing_information ):
        triage_level = "INSUFFICIENT_INFORMATION"
    elif risk_score >= 50:
        triage_level = "URGENT"
    elif risk_score >= 20:
        triage_level = "SAME_DAY"
    else:
        triage_level = "ROUTINE"

    # Step 6: Confidence
    # This is an engineering indicator, not a clinically validated probability.

    confidence = max(
        0.0,
        min(
            1.0,
            1.0 - uncertainty
        )
    )

    if critical_flags:
        confidence = max(
            confidence,
            0.90
        )

    # Step 7: Recommendations

    if triage_level == "EMERGENCY":
        recommendations = [
            "Immediate in-person clinical assessment is warranted."  ]
    elif triage_level == "URGENT":
        recommendations = [
            "Prompt clinical assessment is recommended."
        ]
    elif triage_level == "SAME_DAY":
        recommendations = [
            "Clinical assessment should occur the same day."
        ]
    elif triage_level == "INSUFFICIENT_INFORMATION":
        recommendations = [
            "Additional clinical information is required before assigning a reliable triage level."
        ]
    else:
        recommendations = [
            "Routine clinical follow-up may be appropriate based on the available information."
        ]

    follow_up_questions = generate_follow_up_questions(patient)
    follow_up_questions = [ follow_up_questions(**question)  for question in follow_up_questions]

    return TriageResponse(
        triage_level=triage_level,
        summary=(
            "Assessment generated by the ClinicalTriage v2 deterministic safety engine."
        ),
        red_flags=[
            flag.model_dump()
            for flag in red_flags
        ],
        recommendations=recommendations,
        missing_information=[
            item.model_dump()
            for item in missing_information
        ],
        confidence=confidence,
    )