TRIAGE_LEVELS = [
    "EMERGENCY",
    "URGENT",
    "SAME_DAY",
    "ROUTINE",
    "SELF_CARE",
    "INSUFFICIENT_INFORMATION"
]


CRITICAL_OXYGEN_LEVEL = 90

CRITICAL_HEART_RATE_HIGH = 150

CRITICAL_HEART_RATE_LOW = 40